{% set name = "conbench" %}
{% set version = "1.63.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/conbench-{{ version }}.tar.gz
  sha256: d11e56087164cf433bbb74d4fc1eb8d6e30521277c9fcbe0be45710a2d4a6e66

build:
  entry_points:
    - conbench=conbench.cli:conbench
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - click
    - numpy
    - psutil
    - py-cpuinfo
    - pytest >=7.0
    - python >=3.8
    - pyyaml
    - requests

test:
  imports:
    - conbench
  commands:
    - pip check
    - conbench --help
  requires:
    - pip

about:
  home: https://github.com/conbench/conbench
  summary: Continuous Benchmarking (CB) Framework
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - dianaclarke
    - mariusvniekerk
    - ElenaHenderson
