{% set name = "conbench" %}
{% set version = "1.61.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/conbench-{{ version }}.tar.gz
  sha256: 4d7b82384b42fa7621f36b53513da14dde7b66fc032ba35eb0b9fdf73818c4b1

build:
  entry_points:
    - conbench=conbench.cli:conbench
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - click
    - numpy
    - psutil
    - py-cpuinfo
    - pytest ==6.2.5
    - python >=3.8
    - pyyaml
    - requests

test:
  imports:
    - conbench
  commands:
    - pip check
    - conbench --help
  requires:
    - pip

about:
  home: https://github.com/conbench/conbench
  summary: Continuous Benchmarking (CB) Framework
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - dianaclarke
    - mariusvniekerk
    - ElenaHenderson
